<?php

namespace Sistema\InscripcionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscMoldeCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscMoldeCuentaRepository extends EntityRepository
{
}
