<?php

namespace Sistema\InscripcionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscFichaAsambleaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscFichaAsambleaRepository extends EntityRepository
{
    function findFichaByDocAndMoldeId($tipdoc, $nrodoc, $moldeId) {
        return $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.afiTipdoc = :tipdoc')
            ->andWhere('o.afiNrodoc = :nrodoc')
            ->andWhere('o.moldeId = :moldeId')
            ->setParameter('tipdoc', $tipdoc)
            ->setParameter('nrodoc', $nrodoc)
            ->setParameter('moldeId', $moldeId)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    function findAllFichasWithAfiliado($criteria = 'o.id') {
        return $this->createQueryBuilder('o')
            ->select('o.id', 'o.afiNrodoc as dni', 'o.fecha', 'o.estado', 'o.delegacion', 'o.moldeId', 'a.afiNombre as nombre', 'a.afiMatricula as matricula', 'a.afiMail as mail', 'a.afiCelular as telefono', 'a.afiSexo as genero', 'a.afiFecnac as fechanac')
            ->leftJoin('SistemaCPCEBundle:Afiliado', 'a', 'WITH', 'o.afiTipdoc = a.afiTipdoc AND o.afiNrodoc = a.afiNrodoc')
            ->groupBy('o.afiNrodoc')
            ->orderBy($criteria)
            ->getQuery()
            ->getScalarResult()
        ;
    }
}