<?php

namespace Sistema\InscripcionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InscMoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscMoldeRepository extends EntityRepository
{
}
