entityName: 'Archivo'
entity: 'Sistema\BackBundle\Entity\Archivo'
repository: 'SistemaBackBundle:Archivo'
index: 'admin_archivo'
new: 'admin_archivo_new'
edit: 'admin_archivo_edit'
show: 'admin_archivo_show'
create: 'admin_archivo_create'
update: 'admin_archivo_update'
delete: 'admin_archivo_delete'
export: 'admin_archivo_export'
sessionFilter: 'ArchivoControllerFilter'
saveAndAdd: true
validator: true
fieldsindex:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true
    a.titulo:
        label: 'Titulo'
        name: 'Titulo'
        type: 'string'
        export: true
    a.seccion:
        label: 'Seccion'
        name: 'Seccion'
        type: 'string'
        export: true
    # a.filePath:
    #     label: 'Filepath'
    #     name: 'Filepath'
    #     type: 'string'
    #     export: true
    a.createdAt:
        label: 'Createdat'
        name: 'Createdat'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    a.updatedAt:
        label: 'Updatedat'
        name: 'Updatedat'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        export: true
    a.activo:
        label: 'Activo'
        name: 'Activo'
        type: 'boolean'
        export: true
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        #class: 'col-lg-12'
        #closerow: true
    a.activo:
        label: 'Activo'
        name: 'Activo'
        type: 'boolean'
        #class: 'col-lg-12'
        #closerow: true
    a.titulo:
        label: 'Titulo'
        name: 'Titulo'
        type: 'string'
        #class: 'col-lg-12'
        #closerow: true
    a.seccion:
        label: 'Seccion'
        name: 'Seccion'
        type: 'string'
        #class: 'col-lg-12'
        #closerow: true
    # a.filePath:
    #     label: 'Filepath'
    #     name: 'Filepath'
    #     type: 'string'
        #class: 'col-lg-12'
        #closerow: true
    a.createdAt:
        label: 'Createdat'
        name: 'Createdat'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12'
        #closerow: true
    a.updatedAt:
        label: 'Updatedat'
        name: 'Updatedat'
        type: 'datetime'
        date: 'Y-m-d H:i:s'
        #class: 'col-lg-12'
        #closerow: true