sistema_inscripcion:
    resource: "@SistemaInscripcionBundle/Controller/"
    type:     annotation
    prefix:   /
    
sistema_foro:
    resource: "@SistemaForoBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_back:
    resource: "@SistemaBackBundle/Controller/"
    type:     annotation
    prefix:   /

# all routes from foro grupo in forobundle
mws_foro_grupo:
    resource: "@MWSimpleForoBundle/Controller"
    type:     annotation
    prefix:   /mwsforo

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

sistema_front:
    resource: "@SistemaFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

fos_user_profile_show:
    path:      /
    defaults:  { _controller: SistemaFrontBundle:Default:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

mw_simple_admin_crud:
    resource: "@MWSimpleAdminCrudBundle/Controller/"
    type:     annotation
    prefix:   /admin

sistema_user:
    resource: "@SistemaUserBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_cpce:
    resource: "@SistemaCPCEBundle/Controller/"
    type:     annotation
    prefix:   /

sistema_clasificado:
    resource: "@SistemaClasificadoBundle/Controller/"
    type:     annotation
    prefix:   /
