security:
    acl:
        connection: default

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
#                always_use_default_target_path: true
#                default_target_path:            /
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/superadmin/, role: ROLE_SUPERADMIN }
        - { path: ^/admin/cuenta, role: ROLE_CONSULTA, ips: [127.0.0.1, 190.57.233.98, 192.168.0.0/24, 192.168.10.0/24] }
        - { path: ^/admin/trabajo, role: ROLE_SECTECNICA, ips: [127.0.0.1, 190.57.233.98, 192.168.0.0/24, 192.168.10.0/24] }
        - { path: ^/inscripciones/listado, role: ROLE_INSCRIPCION }
        - { path: ^/admin/inscripciones, role: ROLE_ADMIN }
        - { path: ^/admin/ofertalaboral, role: ROLE_SERVICIO }
        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/matriculado/trabajos, role: ROLE_ADMIN }
#        - { path: ^/matriculado/trabajos, role: ROLE_MATRICULADO, ips: [127.0.0.1, 192.168.0.0/24]  }
        - { path: ^/matriculado/, role: ROLE_MATRICULADO }
        - { path: ^/profile/, role: ROLE_MATRICULADO }
        - { path: ^/usuario/, role: ROLE_USER }
        - { path: ^/firmadigital/, role: ROLE_MATRICULADO }

    role_hierarchy:
        ROLE_MATRICULADO: ROLE_USER
        ROLE_CONSULTA:    ROLE_USER
        ROLE_SECTECNICA:  ROLE_USER
        ROLE_SERVICIO:    ROLE_USER
        ROLE_INSCRIPCION: ROLE_USER
        ROLE_ADMIN:       ['ROLE_SECTECNICA','ROLE_CONSULTA','ROLE_MATRICULADO','ROLE_SERVICIO','ROLE_INSCRIPCION']
        ROLE_SUPERADMIN:  ROLE_ADMIN