# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
#ACL manager
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
#ACL adminCrud
    mws_acl_manager:
        class: MWSimple\Bundle\AdminCrudBundle\Services\ACLManager
        arguments:
            - "@service_container"
#Listener delete ACL PostRemove
    mws_acl_listener:
        class: MWSimple\Bundle\AdminCrudBundle\EventListener\ACLListener
        arguments:
            - "@service_container"
        tags:
            - { name: doctrine.event_listener, event: preRemove }
#Listener post login
    cpce_login_listener:
        class: Sistema\CPCEBundle\Listener\LoginListener
        arguments: ["@session", "@doctrine"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    cpce_loggedin_listener:
        class: Sistema\CPCEBundle\Listener\LoggedInListener
        arguments: ["@router", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#FOS User Register
    sistema_user.form.handler.registration:
        class: Sistema\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false