entityName: 'Curriculum Vitae'
entity: 'Sistema\ClasificadoBundle\Entity\UserCurriculum'
repository: 'SistemaClasificadoBundle:UserCurriculum'
index: 'front_dato'
new: 'matriculado_curriculum_new'
edit: 'matriculado_curriculum_edit'
create: 'matriculado_curriculum_create'
update: 'matriculado_curriculum_update'
delete: 'matriculado_curriculum_delete'
export: 'matriculado_curriculum_export'
sessionFilter: 'UserCurriculumControllerFilter'
saveAndAdd: false
fieldsindex:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
        export: true
    a.filePath:
        label: 'Filepath'
        name: 'Filepath'
        type: 'string'
        export: true
    a.usercv:
        label: 'Usercv'
        name: 'Usercv'
        type: 'ONE_TO_ONE'
fieldsshow:
    a.id:
        label: 'Id'
        name: 'Id'
        type: 'integer'
    a.filePath:
        label: 'Filepath'
        name: 'Filepath'
        type: 'string'
    a.usercv:
        label: 'Usercv'
        name: 'Usercv'
        type: 'ONE_TO_ONE'
    a.ofertaLaborals:
        label: 'Ofertalaborals'
        name: 'Ofertalaborals'
        type: 'MANY_TO_MANY'
