<?php

namespace Sistema\ClasificadoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaLaboralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfertaLaboralRepository extends EntityRepository
{
    public function getOfertasOrderByFecha() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('o')
            ->from('Sistema\ClasificadoBundle\Entity\OfertaLaboral', 'o')
            ->orderby('o.fechaFin', 'DESC')
            ->where('o.activo = true')
            ->andWhere('o.fechaFin >= :fechaNow')
            ->setParameter('fechaNow', new \DateTime('today'))
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

	public function getIsPostuladoByOferta($id, $userId) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('oferta, curriculum')
            ->from('Sistema\ClasificadoBundle\Entity\OfertaLaboral', 'oferta')
            ->Join('oferta.cvPostulantes', 'curriculum')
            ->where('oferta.id = :id')
            ->andWhere('curriculum.id = :userId')
            ->setParameter('id', $id)
            ->setParameter('userId', $userId)
        ;
        return $qb
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }    
}