<?php

namespace Sistema\CPCEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComprobaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobaRepository extends EntityRepository
{
    //Obtiene los totales completos segun cuenta
    function getComprobantesLiquidacionesByAfiliadoAndTrabajo($tipdoc, $nrodoc, $nro_legalizacion) {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.comTipdoc = :tipdoc')
            ->andWhere('a.comNrodoc = :nrodoc')
            ->andWhere('a.comEstado <> :estado')
            ->andWhere("a.comProceso = '02LIHN'")
            ->andWhere("a.comNrotrabajo = :nro_legalizacion")
            ->setParameter('tipdoc', $tipdoc)
            ->setParameter('nrodoc', $nrodoc)
            ->setParameter('nro_legalizacion', $nro_legalizacion)
            ->setParameter('estado', '9')
            ->getQuery()
            ->getResult()
        ;
    }

    //Obtiene los totales completos segun cuenta
    function getComprobanteByNrocom($tipdoc, $nrodoc, $id) {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.comTipdoc = :tipdoc')
            ->andWhere('a.comNrodoc = :nrodoc')
            ->andWhere('a.comEstado <> :estado')
            ->andWhere("a.comProceso = '02LIHN'")
            ->andWhere("a.comNrocom = :id")
            ->setParameter('tipdoc', $tipdoc)
            ->setParameter('nrodoc', $nrodoc)
            ->setParameter('id', $id)
            ->setParameter('estado', '9')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    //Obtiene los totales completos segun cuenta
    function getComPByNrocom($id) {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->Where("a.comNrocom = :id")
            ->andWhere('a.comEstado <> :estado')
            ->andWhere("a.comProceso = '02LIHN'")
            ->setParameter('id', $id)
            ->setParameter('estado', '9')
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}