<?php

namespace Sistema\CPCEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThcalcacRepository extends EntityRepository
{
    /**
     * Calculo y retonro el honorario minimo.
     */
    function getHonorarioMinimo($monto, $tarea) {
        switch ($tarea->getTarPorcentajehonorario()) {
            //no se calcula
            case 0:
                $montoQuery = -1;
                break;
            //se calcula el 40% del monto fijo minimo
            case 0.40:
                $montoQuery = 0;
                break;
            //default son los que utilizan calculo
            default:
                $montoQuery = $monto;
                break;
        }
        if ($montoQuery >= 0) {
            $arancel = $this->createQueryBuilder('a')
                ->where(':monto BETWEEN a.thcMondes AND a.thcMonhas')
                ->setParameter('monto', $montoQuery)
                ->getQuery()
                ->getSingleResult()
            ;
            //Si es == 0 es Informe Especial el honorarioMinimo lo traigo de la tarea segun campo tar_minimo
            if ($montoQuery == 0) {
                //$honorarioMinimo = $arancel->getThcFijo();
                $honorarioMinimo = $tarea->getTarMinimo();
            } else {
                if ($monto > $arancel->getThcExcedente()) {
                    $excedente = $monto - $arancel->getThcExcedente();
                    $honorarioMinimo = ($monto - $arancel->getThcExcedente()) * $arancel->getThcAdicporc() / 100 + $arancel->getThcFijo();
                } else {
                    $honorarioMinimo = $tarea->getTarMinimo();
                }
            }
        } else {
            $honorarioMinimo = 0;
        }

        return round($honorarioMinimo, 2);
    }
}