<?php

namespace Sistema\CPCEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrabajoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajoRepository extends EntityRepository
{
    function getTrabajoByAfiliado($id, $user) {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.id = :id')
            ->andWhere('a.user = :user')
            ->setParameter('id', $id)
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }

    function getTrabajoByNroLegalizacion($id) {
        return $this->createQueryBuilder('a')
            ->select('a')
            ->where('a.nroLegalizacion = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
}
