<?php

namespace Sistema\CPCEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrabajoEstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrabajoEstadoRepository extends EntityRepository
{
}
