<?php

namespace Sistema\BackBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends EntityRepository
{
	public function getArchivosBySeccion($seccion) {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('a')
            ->from('Sistema\BackBundle\Entity\Archivo', 'a')
            ->orderby('a.titulo', 'DESC')
            ->where('a.activo = true')
            ->andWhere('a.seccion = :seccion')
            ->setParameter('seccion', $seccion)
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    } 

    public function getAllArchivosBySeccionFilter() {
        
        $seccion_1 = 'CPCE';
        $seccion_2 = 'SIPRES';
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('a')
            ->from('Sistema\BackBundle\Entity\Archivo', 'a')
            ->orderby('a.titulo', 'DESC')
            ->where('a.activo = true')
            ->andWhere('a.seccion <> :seccion_1 AND a.seccion <> :seccion_2')
            ->setParameter('seccion_1', $seccion_1)
            ->setParameter('seccion_2', $seccion_2)
        ;
        return $qb
            ->getQuery()
            ->getResult()
        ;
    } 
}